### YamlMime:ModuleUnit
uid: learn-wwl.introduction-to-business-applications.3-the-evolution-of-business-applications-from-crm-and-erp-to-an-integrated-solution
title: The evolution of Business Applications - From CRM and ERP to an integrated solution
metadata:
  title: The evolution of Business Applications - From CRM and ERP to an integrated solution
  description: You can use Audio Conferencing to dial into a Teams meeting from any phone across the world. 
  ms.date: 1/28/2019
  author: Randall-Knapp
  ms.author: rknapp
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
durationInMinutes: 3
content: |
  [!include[](includes/3-the-evolution-of-business-applications-from-crm-and-erp-to-an-integrated-solution.md)]